ticket_website/models.py
from ticket_website import db
from flask_login import UserMixin


# The user model. This is the model which will be created in the database as the users table
class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(255))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    is_admin = db.Column(db.Boolean)

    def is_active(self):
        return super().is_active


# The tickets model. This is the model which will be created in the database as the tickets table
class Ticket(db.Model):
    __tablename__ = 'tickets'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(1000))
    description = db.Column(db.String(10000))
    created_by_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    assigned_to_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    contact_number = db.Column(db.String(150))
    affected_item = db.Column(db.String(1000))
    status = db.Column(db.String(150))

    created_by = db.relationship('User', foreign_keys="Ticket.created_by_id")
    assigned_to = db.relationship('User', foreign_keys="Ticket.assigned_to_id")

ticket_website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_wtf.csrf import CSRFProtect
import os

db = SQLAlchemy()


def create_app():
    # Create the app and initialise CSRF Tokens and Bootstrap
    app = Flask(__name__)
    csrf = CSRFProtect(app)
    csrf.init_app(app)
    Bootstrap(app)

    app.config['SECRET_KEY'] = os.urandom(24)

    # This DB_URI Section below is to fix a bug within the heroku Database_Url which it returns.
    # SqlAlchemy versions > 1.4 (I am using 2.5.1) requires the database url to be prefixed with
    # postgresql:// instead of postgres://
    # The fix was found from the Heroku website
    # https://help.heroku.com/ZKNTJQSK/why-is-sqlalchemy-1-4-x-not-connecting-to-heroku-postgres

    DB_URI = os.environ.get('DATABASE_URL')
    if DB_URI.startswith("postgres://"):
        DB_URI = DB_URI.replace("postgres://", "postgresql://", 1)
    app.config['SQLALCHEMY_DATABASE_URI'] = DB_URI
    app.config['SESSION_COOKIE_SECURE'] = False

    # Init the Db
    db.init_app(app)

    from ticket_website.main.routes import routes
    from ticket_website.auth.auth import auth
    from ticket_website.tickets.tickets import tickets
    from ticket_website.admin.admin import admin

    # Import the blueprints for the endpoints
    app.register_blueprint(routes, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(tickets, url_prefix='/')
    app.register_blueprint(admin, url_prefix='/')

    from ticket_website.models import User, Ticket

    # Create the required database
    create_database(app)

    # Initialise the loginmanager so users can login
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        try:
            return User.query.get(user_id)
        except:
            return None

    return app


# Function to create the database when the app is first run
def create_database(app):
    db.create_all(app=app)
    print("Created Database")

ticket_website/main/routes.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import login_required, current_user
from .main_helper import ticket_count_dict_helper


routes = Blueprint('routes', __name__)


# Endpoint for the regular user homepage
@routes.route('/')
@login_required
def home():
    user_id = current_user.get_id()
    ticket_count_dict = ticket_count_dict_helper(user_id)
    if current_user.is_admin:
        return redirect(url_for('admin.admin_home'))
    return render_template("home.html", ticket_count_dict=ticket_count_dict)

ticket_website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand text-light" href="{{ url_for('routes.home') }}">Ticket System</a>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            {% if current_user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-item nav-link" id="home" href="{{ url_for('routes.home') }}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Tickets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('tickets.create_ticket') }}">Create Ticket</a>
                  {% if current_user.is_admin %}
                  <a class="dropdown-item" href="{{ url_for('tickets.view_open_tickets') }}">View Open Tickets</a>
                  <a class="dropdown-item" href="{{ url_for('admin.view_assigned_tickets') }}">View All Assigned Tickets</a>
                  <a class="dropdown-item" href="{{ url_for('admin.view_admin_tickets', status='all') }}">View All Tickets</a>
                  {% else %}
                  <a class="dropdown-item" href="{{ url_for('tickets.view_open_tickets') }}">View Open Tickets</a>
                  <a class="dropdown-item" href="{{ url_for('tickets.view_tickets', status='all') }}">View All Tickets</a>
                  {% endif %}
                  
                </div>
              </li>
              {% if current_user.is_admin %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Users
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('admin.create_new_user') }}">Create new User</a>
                    <a class="dropdown-item" href="{{ url_for('admin.view_regular_users') }}">View Regular Users</a>
                    <a class="dropdown-item" href="{{ url_for('admin.view_admin_users') }}">View Admin Users</a>
                  </div>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-item nav-link" id="logout" href="{{ url_for('auth.logout') }}">Logout</a> 
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-item nav-link" id="login" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-item nav-link" id="signup" href="{{ url_for('auth.signup') }}">Signup</a>
              </li>
            {% endif %}
          </ul>
          {% if current_user.is_authenticated %}
            <span class="navbar-text text-light">
              Welcome {{ current_user.first_name }}
            </span>
          {% endif %}
        </div>
      </nav>

      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %} 
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert" id="success-error">
              {{ message }}
            </div>
          {% else %} 
            <div class="alert alert-success" role="alert" id="success-alert">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      {% endwith %}

      <div class="container">{% block content %} {% endblock %}</div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>

      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>

      <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>

      <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
  </body>
</html>

ticket_website/templates/create_ticket.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Create Ticket {% endblock %}

{% block content %}
<form method="POST">
  {{ form.csrf_token }}
    <div class="container">
        <h3 align="center">Create New Ticket</h3>
        <hr>
          {{ wtf.quick_form(form) }}
          <button type="submit" class="btn btn-primary">Submit</button>
        <hr>
      </div>
</form>
{% endblock %}

ticket_website/templates/edit_ticket.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Edit Ticket {% endblock %}

{% block content %}
<form method="POST">
  {{ form.csrf_token }}
    <div class="container">
        <h3 align="center">Edit Ticket</h3>
        <hr>
          {{ wtf.quick_form(form) }}
          <button type="submit" class="btn btn-primary">Submit</button>
        <hr>
      </div>
</form>
{% endblock %}

ticket_website/templates/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
<h1>Please select what you would like to do</h1>

<div class="container">
    <div class="card-deck">
        <div class="card text-center border-dark mb-3">
            <div class="card-header">Create Ticket</div>
            <div class="card-body">
                <p class="card-text">Raise a new Ticket for Service Desk.</p>
                <a href="{{ url_for('tickets.create_ticket') }}" class="btn btn-primary">Create New Ticket</a>
            </div>
        </div>
        <div class="card text-center border-dark mb-3">
            <div class="card-header">View Open Tickets</div>
            <div class="card-body">
                <p class="card-text">View all tickets which you have created.</p>
                <a href="{{ url_for('tickets.view_open_tickets') }}" class="btn btn-primary">View Open Tickets</a>
            </div>
        </div>
        <div class="card text-center border-dark mb-3">
            <div class="card-header">View All Tickets</div>
            <div class="card-body">
                <p class="card-text">View all tickets which you have created.</p>
                <a href="{{ url_for('tickets.view_tickets', status='all') }}" class="btn btn-primary">View Tickets</a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="container">
    <h2>Ticket Information for {{ current_user.first_name }} </h2>
    <div class="card-deck">
    {% for status, count in ticket_count_dict.items() %}
        {% if status == 'Open' %}
            <div class="card text-center border-primary mb-2">
        {% elif status == 'In Progress' %}
            <div class="card text-center border-warning mb-2">
        {% elif status == 'Resolved' %}
            <div class="card text-center border-success mb-2">
        {% elif status == 'Closed' %}
            <div class="card text-center border-danger mb-2">
        {% endif %}
            <div class="card-header">
            <h3 class="card-title">{{ status }}</h3>
            </div>
            <div class="card-body">
            <h5 class="card-title">{{ count }} </h5>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %} 

ticket_website/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login {% endblock %}

{% block content %}
<form method="POST">
  {{ form.csrf_token }}
    <div class="container">
        <h3 align="center">Login</h3>
        <hr>
          {{ wtf.quick_form(form) }}
          <button type="submit" class="btn btn-primary">Submit</button>
        <hr>
      </div>
</form>
{% endblock %}

ticket_website/templates/signup.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Signup {% endblock %}

{% block content %}
<form method="POST">
  {{ form.csrf_token }}
    <div class="container">
        <h3 align="center">Signup</h3>
        <hr>
          {{ wtf.quick_form(form) }}
          <button type="submit" class="btn btn-primary">Submit</button>
        <hr>
      </div>
</form>
{% endblock %}

ticket_website/templates/view_open_tickets.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} View Open Tickets {% endblock %}

{% block content %}

<h1>Showing all created tickets for {{ current_user.first_name }} </h1>
<br />

<br />
{% for ticket in tickets %}
<br />
<div class="container">
    <div class="card border-primary">
        <div class="card-body text-center">
            <h4 class="card-title">{{ ticket.title }}</h4>
            <div class="table-responsive">
                <table class="table">
                <thead class="thead">
                    <tr background-colour="#005eb8">
                        <th scope="col">Ticket ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Assigned To</th>
                        <th scope="col">Contact Number</th>
                        <th scope="col">Affected Item</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>{{ ticket.id }} </th>
                            <td>{{ ticket.title }}</td>
                            <td>{{ ticket.description }}</td>
                            {% if ticket.assigned_to == null or ticket.assigned_to == None %}
                                <td>Unassigned</td>
                            {% else %}
                                <td>{{ ticket.assigned_to.first_name + " " + ticket.assigned_to.last_name }}</td>
                            {% endif %}
                            <td>{{ ticket.contact_number }}</td>
                            <td>{{ ticket.affected_item }}</td>
                            <td class="bg-info"> {{ ticket.status }} </td>
                        </tr>
                </tbody>
                </table>
            </div>
            <a href="{{ url_for('tickets.edit_ticket', ticket_id = ticket.id ) }}" class="btn btn-primary">Edit Ticket</a>
            {% if ticket.status == 'Open' or ticket.status == 'In Progress' %}
                <a href="{{ url_for('tickets.change_ticket_status', ticket_id = ticket.id, status = 'Resolved' ) }}" class="btn btn-primary">Resolve Ticket</a>
                <a href="{{ url_for('tickets.change_ticket_status', ticket_id = ticket.id, status = 'Closed' ) }}" class="btn btn-primary">Close Ticket</a>
            {% elif ticket.status == 'Resolved' %}
                <a href="{{ url_for('tickets.change_ticket_status', ticket_id = ticket.id, status = 'Closed' ) }}" class="btn btn-primary">Close Ticket</a>
            {% endif %}
        </div>
    </div>
</div>
<br />
{% endfor %}
{% endblock %}

ticket_website/templates/view_tickets.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} View Ticket {% endblock %}

{% block content %}

<h1>Showing all created tickets for {{ current_user.first_name }} </h1>
<br />

<h3>Filter by ticket status</h3>
<a href="{{ url_for('tickets.view_tickets', status = 'Open' ) }}" class="btn btn-primary">Open</a>
<a href="{{ url_for('tickets.view_tickets', status = 'In Progress' ) }}" class="btn btn-primary">In Progress</a>
<a href="{{ url_for('tickets.view_tickets', status = 'Resolved' ) }}" class="btn btn-primary">Resolved</a>
<a href="{{ url_for('tickets.view_tickets', status = 'Closed' ) }}" class="btn btn-primary">Closed</a>
<a href="{{ url_for('tickets.view_tickets', status='all' ) }}" class="btn btn-danger">Reset</a>
<br />
{% for ticket in tickets %}
<br />
<div class="container">
    {% if ticket.status == 'Open' %}
        <div class="card border-primary">
    {% elif ticket.status == 'In Progress' %}
        <div class="card border-warning">
    {% elif ticket.status == 'Resolved' %}
        <div class="card border-success">
    {% elif ticket.status == 'Closed' %}
        <div class="card border-danger">
    {% endif %}
        <div class="card-body text-center">
            <h4 class="card-title">{{ ticket.title }}</h4>
            <div class="table-responsive">
                <table class="table">
                <thead class="thead">
                    <tr background-colour="#005eb8">
                        <th scope="col">Ticket ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Assigned To</th>
                        <th scope="col">Contact Number</th>
                        <th scope="col">Affected Item</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>{{ ticket.id }} </th>
                            <td>{{ ticket.title }}</td>
                            <td>{{ ticket.description }}</td>
                            {% if ticket.assigned_to == null or ticket.assigned_to == None %}
                                <td>Unassigned</td>
                            {% else %}
                                <td>{{ ticket.assigned_to.first_name + " " + ticket.assigned_to.last_name }}</td>
                            {% endif %}
                            <td>{{ ticket.contact_number }}</td>
                            <td>{{ ticket.affected_item }}</td>
                            {% if ticket.status == 'Open' %}
                                <td class="bg-info"> {{ ticket.status }} </td>
                            {% elif ticket.status == 'In Progress' %}
                                <td class="bg-warning"> {{ ticket.status }} </td>
                            {% elif ticket.status == 'Resolved' %}
                                <td class="bg-success"> {{ ticket.status }} </td>
                            {% elif ticket.status == 'Closed' %}
                                <td class="bg-danger"> {{ ticket.status }} </td>
                            {% endif %}
                        </tr>
                </tbody>
                </table>
            </div>
            <a href="{{ url_for('tickets.edit_ticket', ticket_id = ticket.id ) }}" class="btn btn-primary">Edit Ticket</a>
            {% if ticket.status == 'Open' or ticket.status == 'In Progress' %}
                <a href="{{ url_for('tickets.change_ticket_status', ticket_id = ticket.id, status = 'Resolved' ) }}" class="btn btn-primary">Resolve Ticket</a>
                <a href="{{ url_for('tickets.change_ticket_status', ticket_id = ticket.id, status = 'Closed' ) }}" class="btn btn-primary">Close Ticket</a>
            {% elif ticket.status == 'Resolved' %}
                <a href="{{ url_for('tickets.change_ticket_status', ticket_id = ticket.id, status = 'Closed' ) }}" class="btn btn-primary">Close Ticket</a>
            {% endif %}
        </div>
    </div>
</div>
<br />
{% endfor %}
{% endblock %}